version: "3.9"
services:
  traefik:
    image: "traefik:v2.10"
    container_name: "traefik"
    command:
      - "--providers.docker=true"
      - "--accesslog=true"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--api.insecure=true"     
      - "--api.dashboard=true"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.entryPoints=traefik"
      - "traefik.http.routers.api.rule=PathPrefix(`/api`) || PathPrefix(`/dashboard`)"
      - "traefik.http.routers.api.service=api@internal"
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  # GUI
  lens:
    image: samply/lens
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.lens-service.loadbalancer.server.port=80"
      - "traefik.http.routers.lens-https-router.rule=Host(`${LENS_DOMAIN}`)"
      - "traefik.http.routers.lens-https-router.tls=true"
      - "traefik.http.routers.lens-https-router.service=lens-service"

  # Backend
  spot:
    image: samply/spot
    container_name: spot
    env_file:
      - env.spot
    labels:
      - "traefik.enable=true"
      - "traefik.http.services.spot-service.loadbalancer.server.port=8100"
      - "traefik.http.routers.spot-https-router.rule=Host(`${LENS_DOMAIN}`) && PathPrefix(`/backend`)"
      - "traefik.http.routers.spot-https-router.tls=true"
      - "traefik.http.routers.spot-https-router.service=spot-service"
      - "traefik.http.middlewares.corsheaders.headers.accesscontrolallowmethods=GET,OPTIONS,POST"
      - "traefik.http.middlewares.corsheaders.headers.accesscontrolalloworiginlist=http://${LENS_DOMAIN}"
      - "traefik.http.middlewares.corsheaders.headers.accesscontrolallowcredentials=true"
      - "traefik.http.middlewares.corsheaders.headers.accesscontrolmaxage=-1"
      - "traefik.http.middlewares.ccp_b_strip.stripprefix.prefixes=/backend"
        #- "traefik.http.routers.spot-https-router.rule=PathPrefix(`/backend`)"
      - "traefik.http.routers.spot-https-router.middlewares=corsheaders,ccp_b_strip"

  # Beam proxy
  ecdc-locator:
    image: docker.verbis.dkfz.de/cache/samply/beam-proxy:develop
    container_name: ecdc-locator
    env_file:
      - env.beam
    volumes:
      - ./conf/trusted-ca-certs:/conf/trusted-ca-certs:ro
      - ./conf/eric.root.crt.pem:/conf/root.crt.pem:ro
      - ./conf/pki/ecdc-locator.priv.pem:/run/secrets/proxy.pem
    labels:
      - "traefik.enable=false"

